// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB9ny9V0xswCB8v-kBGfFnkU4gNQ7uMFQ',
    appId: '1:736981965568:web:51a4a68e69050d754df1e5',
    messagingSenderId: '736981965568',
    projectId: 'spotify-clone-c87be',
    authDomain: 'spotify-clone-c87be.firebaseapp.com',
    storageBucket: 'spotify-clone-c87be.appspot.com',
    measurementId: 'G-8L1M2KMG5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6OCWi4HkKusglqDTR0pfhw6ow4oxeGnk',
    appId: '1:736981965568:android:0bbf2a2a339a14a54df1e5',
    messagingSenderId: '736981965568',
    projectId: 'spotify-clone-c87be',
    storageBucket: 'spotify-clone-c87be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9n-MjcfRTHLhGtlK6I4EV0Wgurz2FTaQ',
    appId: '1:736981965568:ios:c61b2a8c6ab4118d4df1e5',
    messagingSenderId: '736981965568',
    projectId: 'spotify-clone-c87be',
    storageBucket: 'spotify-clone-c87be.appspot.com',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBB9ny9V0xswCB8v-kBGfFnkU4gNQ7uMFQ',
    appId: '1:736981965568:web:0c8ace836a9a4a824df1e5',
    messagingSenderId: '736981965568',
    projectId: 'spotify-clone-c87be',
    authDomain: 'spotify-clone-c87be.firebaseapp.com',
    storageBucket: 'spotify-clone-c87be.appspot.com',
    measurementId: 'G-XDPZ80VCBW',
  );
}
